### ISSUE TITLE
Any way to support ruby 1.9.X?

### ISSUE THREAD

**Issue by dcosson** [AndrewKvalheim/middleman-vcs-time#1]
Would it be much work to let this support ruby 1.9?

**Comment by AndrewKvalheim** [comment]
Probably not, but [support for Ruby 1.9.x has ended](https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/) so it would feel like a step backwards. I'd accept a PR if there's a strong reason for it.

**Comment by dcosson** [comment]
Ah ok, makes sense. I thought I had a dependency on it elsewhere but I ended up being able to upgrade to 2.x and use this plugin. Thanks!
